# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaAccessVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssd', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
