# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0003_auto_20170214_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaAccessVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenterlight.BetaAccess')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenterlight.BetaAccessVMType')),
            ],
        ),
    ]
