# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-31 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0004_betaaccessvm'),
    ]

    operations = [
        migrations.AddField(
            model_name='betaaccess',
            name='name',
            field=models.CharField(default='name', max_length=250),
            preserve_default=False,
        ),
    ]
