# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0005_betaaccess_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('opennebula_vm_template_id', models.IntegerField()),
            ],
        ),
    ]
