# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-27 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0007_contactus'),
        ('datacenterlight', '0008_auto_20170821_2024'),
    ]

    operations = [
    ]
