# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-27 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0009_merge'),
        ('datacenterlight', '0008_contactus_field'),
    ]

    operations = [
    ]
