# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-20 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0010_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betaaccessvm',
            name='access',
        ),
        migrations.RemoveField(
            model_name='betaaccessvm',
            name='type',
        ),
        migrations.DeleteModel(
            name='BetaAccess',
        ),
        migrations.DeleteModel(
            name='BetaAccessVM',
        ),
        migrations.DeleteModel(
            name='BetaAccessVMType',
        ),
    ]
