# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20160404_1908'),
        ('datacenterlight', '0012_dclcalculatorpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCLNavbarPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('logo_url', models.URLField(blank=True, max_length=300, null=True)),
                ('logo_dark', filer.fields.image.FilerImageField(blank=True, help_text='Logo to be used on white navbar',
                                                                 null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
                ('logo_light', filer.fields.image.FilerImageField(blank=True, help_text='Logo to be used on transparent navbar',
                                                                  null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
