# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-19 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0013_dclnavbarpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dclnavbarpluginmodel',
            name='language_dropdown',
            field=models.BooleanField(
                default=True, help_text='Select to include the language selection dropdown.'),
        ),
    ]
