# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-18 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0013_dclnavbarpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCLCalculatorPluginModel',
            fields=[
                ('dclsectionpluginmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datacenterlight.DCLSectionPluginModel')),
                ('show_hdd', models.BooleanField(default=False, help_text="Show 'Add HDD' option")),
                ('default_hdd_value', models.IntegerField(default=10, help_text='The default value of HDD that is set when the calculator loads')),
            ],
            options={
                'abstract': False,
            },
            bases=('datacenterlight.dclsectionpluginmodel',),
        ),
    ]
