# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-27 15:31
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0015_auto_20180323_0011'),
        ('cms', '0014_auto_20160404_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_placeholder', cms.models.fields.PlaceholderField(editable=False, null=True,
                                                                          on_delete=django.db.models.deletion.CASCADE, slotname='datacenterlight_navbar', to='cms.Placeholder')),
                ('footer_placeholder', cms.models.fields.PlaceholderField(editable=False, null=True,
                                                                          on_delete=django.db.models.deletion.CASCADE, slotname='datacenterlight_footer', to='cms.Placeholder')),
                ('name', models.CharField(default='default',
                                          help_text='A unique name for the Integration. This name will be used to fetch the Integration into pages', max_length=100, unique=True)),
            ],
        ),
    ]
