# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-20 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0019_auto_20180415_2236'),
        ('datacenterlight', '0019_cmsfaviconextension'),
    ]

    operations = [
    ]
