# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-25 09:20
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0020_merge'),
        ('cms', '0014_auto_20160404_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsintegration',
            name='calculator_placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='dcl-calculator-placeholder+', slotname='datacenterlight_calculator', to='cms.Placeholder'),
        ),
        migrations.RenameModel(
            old_name='DCLCustomPricingModel',
            new_name='DCLCalculatorPluginModel',
        ),
    ]
