# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-07 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0021_cmsintegration_calculator_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmpricing',
            name='discount_amount',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='vmpricing',
            name='discount_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
