# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0022_auto_20180506_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='dclcalculatorpluginmodel',
            name='vm_type',
            field=models.CharField(choices=[('public', 'Public'), ('ipv6only', 'Ipv6Only')], default='public', max_length=50),
        ),
        migrations.AddField(
            model_name='vmtemplate',
            name='vm_type',
            field=models.CharField(choices=[('public', 'Public'), ('ipv6only', 'Ipv6Only')], default='public', max_length=50),
        ),
    ]
