# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-06-13 09:09
from __future__ import unicode_literals

import datacenterlight.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0023_auto_20180524_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmpricing',
            name='vm_templates_to_show',
            field=datacenterlight.models.MultipleChoiceArrayField(base_field=models.CharField(blank=True, choices=[('4', 'CentOS 7'), ('14', 'Debian 8'), ('25', 'Ubuntu 14.04'), ('26', 'Ubuntu 16.04'), ('36', 'Devuan Jessie'), ('65', 'Devuan Ascii'), ('69', 'FreeBSD 11.1')], max_length=256), blank=True, default=list, help_text='Not selecting any items above will result in showing all templates', size=None),
        ),
    ]
