# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-06-28 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0024_dclcalculatorpluginmodel_vm_templates_to_show'),
        ('datacenterlight', '0024_dclcontactpluginmodel_html_id'),
    ]

    operations = [
    ]
