# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-25 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0024_dclcalculatorpluginmodel_vm_templates_to_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='dclnavbarpluginmodel',
            name='show_login_option',
            field=models.BooleanField(default=True, help_text='Uncheck this if you do not want to show login/dashboard.'),
        ),
    ]
