# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-27 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0025_dclnavbarpluginmodel_show_login_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='dclcalculatorpluginmodel',
            name='enable_512mb_ram',
            field=models.BooleanField(default=False),
        ),
    ]
