# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-29 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0026_dclcalculatorpluginmodel_default_selected_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='dclcalculatorpluginmodel',
            name='enable_512mb_ram',
            field=models.BooleanField(default=False),
        ),
    ]
