BBBB BBBB BBBBBBBBB

XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    BB BBBBBBBBBBB
    XXXX
	 gettext('by')  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX
    XXXXX
    BBBBB
XXXXX
XXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBB
	BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBB
	    BB BBBBBBBBBBBBB
		XXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBB BBBBBBBBBBBBX BBBBBXXXXX
	    BBBBB
	BBBBBB
    BBBBB
    BB BBBBBBBBBBBBBBBB
	BBB BBB BB BBBBBBBBBBBBB
	    XXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXBB BBB BBBBBBBBBBBBX BBBBBXXXXX
	BBBBBB
    BBBBB
XXXXX