XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    BBBB BBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXX XXXXXXXXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XX XXXXXXX XXXXXXXXXXXX XXXXX
                                        XXXXXXXXXXXX
                                    XXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX

                                    BB BBBBB
                                        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX
                                    BBBB
                                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

                                        XXXXXXXXX
                                    BBBBB
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX
                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX
                                XXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX
                                XXXX
                                XX XXXXXXXXXX XXXXXXXXXXXX
                                   XXXXXXBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX


XXXXXXX
XXXXXXX