XXXXXX
XXXXXX
    BBBB BBBBBB
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
          XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXX XXXXXXXXX X
            XXX XXXXX X XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX X
                XXXXXXXXX
                XX XXXX XXX XXXXXX XX XXX XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            X XXXX X
                XX XXXXX XXXXXXXX XXX XXXXXX XXX XXXX XXXX
                XXX XXXXX X XXXXXXXXXXXX
                XX XXXXXX XXX XXXXX XXXX XXX XXXX XX XX XXXX XXXXXXXXX XX XXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XX XXX XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
            X
        XX
        XXXXXXXXXXXXXXX XXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X
                XXX XXXXX X XXXXXXXX
                XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXX XXX XXXXXX XXXXXX XX XXXXXXX XXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXX
                    XXXXXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXX XXX XXXX XXXX XXXXXXXXXX XXXX XXX XXXXXXX XXXXXX
                XXXXXX XXXXXX
            XXX
        XXX
    XXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    BBBB BBBBBB
    XXXXX XXXXXXBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX
                    XXXXXXXXXX X XXXX XXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXX X  XXXXXXXX
                XXXXXX
                XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    BBB BBBBB BB  BBBB
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            
                            BBB BBBBB BB BBBBBBBBBBBB
                                FFFFFFFFF
                            BBBBBB
                        XXXXXX
                    BBBBBB
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX

                XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX
                    XXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX


XXXXXXX
XXXXXXX