XXXXXX
XXXXXX
    BBBB BBBBBB
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
          XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXX XXX XXXXXXXXX 
                    XXXXXXXX XXXXXXXXX XXXXXXX XX XX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX


                XXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXX
            XXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXX
    XXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XXXX
XXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX


XXXX


XXXXXXX
XXXXXXX