BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB BBBBBBBB BBBBBBBBBB
BBBBB BBBBBXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB

XXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXX X XXXXXXXXXXXX
                XXXXX XXXX XXX XXXX XX XX XXXXXX XXXXXXX
                XXXXXXX XXXXXXX
                XXXX
                XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                BBBBBBBBBB
                    BBB BBBBB BB BBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            BBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBB
                        XXXXXX
                    BBBBBB
                    
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXXXX

                XXXXXXX XXX X XXXXXXXXXXXX

                XXXXX XXXX XXXXX XXXX XXXXX XX XXXXXXXXX
                    XXXXXX XXX X XXXX XXXX XX XXX XXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXXXXXX
                XXXX
                XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                    BBBBBBBBBB
                     XXXX XXXXXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBB
                            BBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBB
                            XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                            XXXX  XXX
                        BBBBBB
                    XXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX

BBBBBBBB