BBBB BBBBBB
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBB BB BBBB
    XXXXXXXX
        XXXX X XXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBXX
                XX XXXXXX
    XXXXXXXXX
    BBBBB
XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    BB BBB BB BBBBBBBBBBB
                        XXXXX XXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    BBBB
                        XXXX XXXXXXX XXX XXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXX XX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
                    BBBBB
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX


XXXXXXX
XXXXXXX