XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    BBBB BBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBB BB BBBB
    XXXXXXXX
        XXXX X XXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXX X XXXX
                XX XXXXXX
    XXXXXXXXX
    BBBBB
XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    BB BBB
                        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    BBBB
                        XXXXXXXX XXX XXXXXXXXXXXX
                    BBBBB
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX


XXXXXXX
XXXXXXX