# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '__first__'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('last4', models.CharField(max_length=4)),
                ('cc_brand', models.CharField(max_length=10)),
                ('stripe_charge_id', models.CharField(max_length=100, null=True)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.BillingAddress')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.StripeCustomer')),
            ],
            options={
                'permissions': (('view_hostingorder', 'View Hosting Order'),),
            },
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VirtualMachinePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cores', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('disk_size', models.IntegerField()),
                ('price', models.FloatField()),
                ('public_key', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending for activation'), ('online', 'Online'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('configuration', models.CharField(choices=[('django', 'Ubuntu 14.04, Django'), ('rails', 'Ubuntu 14.04, Rails'), ('nodejs', 'Debian, NodeJS')], max_length=20)),
            ],
            options={
                'permissions': (('view_virtualmachineplan', 'View Virtual Machine Plan'), ('cancel_virtualmachineplan', 'Cancel Virtual Machine Plan')),
            },
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VirtualMachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('base_price', models.FloatField()),
                ('memory_price', models.FloatField()),
                ('core_price', models.FloatField()),
                ('disk_size_price', models.FloatField()),
                ('hosting_company', models.CharField(choices=[('hetzner_nug', 'Hetzner No Uptime Guarantee'), ('hetzner', 'Hetzner'), ('hetzner_raid6', 'Hetzner Raid6'), ('hetzner_glusterfs', 'Hetzner Glusterfs'), ('bern', 'Bern')], max_length=30)),
                ('location', models.CharField(choices=[('DE', 'Germany'), ('CH', 'Switzerland')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='virtualmachineplan',
            name='vm_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.VirtualMachineType'),
        ),
        migrations.AddField(
            model_name='hostingorder',
            name='vm_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_orders', to='hosting.VirtualMachinePlan'),
        ),
    ]
