# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailsBetaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('received_date', models.DateTimeField(verbose_name='date received')),
            ],
        ),
    ]
