# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_railsbetauser'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachineTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('base_price', models.FloatField()),
                ('memory_price', models.FloatField()),
                ('cores_price', models.FloatField()),
                ('disk_size_price', models.FloatField()),
                ('hosting_company', models.CharField(choices=[('hetzner_nug', 'Hetzner No Uptime Guarantee'), ('hetzner', 'Hetzner'), ('hetzner_raid6', 'Hetzner Raid6'), ('hetzner_glusterfs', 'Hetzner Glusterfs'), ('bern', 'Bern')], max_length=10)),
            ],
        ),
    ]
