# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosting', '0007_auto_20160418_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachinePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cores', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('disk_size', models.IntegerField()),
                ('price', models.FloatField()),
                ('client', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('vm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.VirtualMachineType')),
            ],
        ),
    ]
