# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_billingaddress'),
        ('membership', '0004_stripecustomer'),
        ('hosting', '0008_virtualmachineplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='virtualmachineplan',
            name='client',
        ),
        migrations.AddField(
            model_name='hostingorder',
            name='VMPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.VirtualMachinePlan'),
        ),
        migrations.AddField(
            model_name='hostingorder',
            name='billing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.BillingAddress'),
        ),
        migrations.AddField(
            model_name='hostingorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.StripeCustomer'),
        ),
    ]
