# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0009_auto_20160426_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingorder',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingorder',
            name='stripe_charge_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
