# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0010_auto_20160426_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingorder',
            name='VMPlan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hosting.VirtualMachinePlan'),
        ),
    ]
