# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0011_auto_20160426_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingorder',
            name='cc_brand',
            field=models.CharField(default='Visa', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostingorder',
            name='last4',
            field=models.CharField(default=1111, max_length=4),
            preserve_default=False,
        ),
    ]
