# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0013_auto_20160505_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingorder',
            name='VMPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_orders', to='hosting.VirtualMachinePlan'),
        ),
    ]
