# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0015_auto_20160512_0448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RailsBetaUser',
        ),
    ]
