# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0016_delete_railsbetauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachinetype',
            name='location',
            field=models.CharField(choices=[('DE', 'Germany'), ('CH', 'Switzerland')], default='DE', max_length=3),
            preserve_default=False,
        ),
    ]
