# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0018_virtualmachineplan_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachineplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for activation'), ('online', 'Online')], default='online', max_length=20),
        ),
    ]
