# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0019_virtualmachineplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachineplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for activation'), ('online', 'Online')], default='pending', max_length=20),
        ),
    ]
