# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0021_auto_20160526_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachineplan',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=50),
            preserve_default=False,
        ),
    ]
