# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0022_virtualmachineplan_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachineplan',
            name='configutarion',
            field=models.CharField(choices=[('django', 'Ubuntu 14.04, Django'), ('rails', 'Ubuntu 14.04, Rails'), ('nodejs', 'Debian, NodeJS')], default='django', max_length=20),
            preserve_default=False,
        ),
    ]
