# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0025_auto_20160621_0522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualmachineplan',
            options={'permissions': (('view_virtualmachineplan', 'View Virtual Machine Plan'), ('cancel_virtualmachineplan', 'Cancel Virtual Machine Plan'))},
        ),
    ]
