# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0026_auto_20160625_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostingorder',
            options={'permissions': (('view_hostingorder', 'View Hosting Order'),)},
        ),
    ]
