# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-05 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20170322_1443'),
        ('membership', '0006_auto_20160526_0445'),
        ('hosting', '0029_managevm'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.BillingAddress')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.StripeCustomer')),
            ],
            options={
                'permissions': (('view_hostingbill', 'View Hosting Bill'),),
            },
            bases=(utils.mixins.AssignPermissionsMixin, models.Model),
        ),
    ]
