# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-06 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0030_hostingbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingbill',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
