# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-04 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0031_auto_20170503_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachinetype',
            name='cores',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinetype',
            name='disk_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinetype',
            name='memory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
