# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-04 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0033_virtualmachinetype_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachinetype',
            name='configuration',
        ),
        migrations.AlterField(
            model_name='virtualmachineplan',
            name='configuration',
            field=models.CharField(choices=[('debian', 'Debian 8'), ('ubuntu', 'Ubuntu 16.06'), ('devuan', 'Devuan 1'), ('centos', 'CentOS 7')], max_length=20),
        ),
        migrations.AlterField(
            model_name='virtualmachineplan',
            name='vm_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosting.VirtualMachineType'),
        ),
    ]
