# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-07 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0031_hostingbill_total_price'),
        ('hosting', '0036_auto_20170506_2312'),
    ]

    operations = [
    ]
