# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-12 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0037_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachineplan',
            name='vm_type',
        ),
        migrations.RemoveField(
            model_name='hostingorder',
            name='vm_plan',
        ),
        migrations.AddField(
            model_name='hostingorder',
            name='vm_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='VirtualMachinePlan',
        ),
        migrations.DeleteModel(
            name='VirtualMachineType',
        ),
    ]
