# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0038_auto_20170512_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingorder',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
