# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0039_hostingorder_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_size', models.FloatField(default=0.0)),
                ('cpu_cores', models.FloatField(default=0.0)),
                ('memory', models.FloatField(default=0.0)),
            ],
        ),
    ]
