# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-20 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0040_hostingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingbill',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 5, 20, 13, 46, 57, 631165, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
