# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-06 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0040_hostingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhostingkey',
            name='private_key',
            field=models.FileField(blank=True, upload_to='private_keys'),
        ),
    ]
