# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-20 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0041_hostingbill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingorder',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hosting.HostingBill'),
        ),
    ]
