# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-16 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenterlight', '0019_auto_20180415_2236'),
        ('hosting', '0043_vmdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingorder',
            name='vm_pricing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datacenterlight.VMPricing'),
            preserve_default=False,
        ),
    ]
