# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-13 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0043_vmdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingorder',
            name='referer_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
