# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-04 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0043_vmdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmdetail',
            name='hdd_size',
            field=models.FloatField(default=0.0),
        ),
    ]
