# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-17 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0044_hostingorder_referer_url'),
        ('hosting', '0044_hostingorder_vm_pricing'),
    ]

    operations = [
    ]
