# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0047_auto_20180821_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingorder',
            name='generic_payment_id',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
    ]
