# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-21 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0047_auto_20180821_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingorder',
            name='cc_brand',
            field=models.CharField(max_length=35),
        ),
    ]
