# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-05 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0048_auto_20181003_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericproduct',
            name='product_slug',
            field=models.SlugField(help_text='An mandatory unique slug for the product', unique=True),
        ),
    ]
