# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_urlconfrevision'),
        ('digitalglarus', '0001_initial'),
    ]

    operations = [
    ]
