# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0004_dggallery_dggalleryplugin_dgpicture_dgsupportersplugin_supporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='received_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
