# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0005_auto_20160407_0519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
