# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-28 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0009_booking_bookingorder_bookingprices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingPrices',
            new_name='BookingPrice',
        ),
    ]
