# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-28 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0010_auto_20160828_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingprice',
            name='special_price_offer',
            field=models.FloatField(default=290.0),
            preserve_default=False,
        ),
    ]
