# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0011_bookingprice_special_price_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='free_days',
            field=models.IntegerField(default=0),
        ),
    ]
