# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-08 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0014_booking_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorder',
            name='amount',
            field=models.FloatField(default=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiporder',
            name='amount',
            field=models.FloatField(default=35.0),
            preserve_default=False,
        ),
    ]
