# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-09 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0015_auto_20160908_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingprice',
            old_name='special_price_offer',
            new_name='special_month_price',
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='original_price',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='special_month_price',
            field=models.FloatField(default=290),
            preserve_default=False,
        ),
    ]
