# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-28 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0017_membership_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorder',
            name='membership_required_months',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='membership_required_months_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
