# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-29 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0018_auto_20160928_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorder',
            name='membership_required_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingorder',
            name='membership_required_months_price',
            field=models.FloatField(default=0),
        ),
    ]
