# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0020_auto_20161013_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 17, 19, 58, 0, 209303, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 17, 19, 58, 7, 361473, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiporder',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 17, 19, 58, 15, 657240, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiporder',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 17, 19, 58, 16, 897120, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
