# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-23 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0021_auto_20161017_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingorder',
            name='membership_required_months',
        ),
        migrations.RemoveField(
            model_name='bookingorder',
            name='membership_required_months_price',
        ),
    ]
