# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-25 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0022_auto_20161023_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Approved'), (2, 'Cancelled')], default=1),
        ),
    ]
