# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-23 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0024_bookingcancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiporder',
            name='stripe_subscription_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
