# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-24 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0025_membershiporder_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorder',
            name='cc_brand',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='membershiporder',
            name='cc_brand',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
