# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-04 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalglarus', '0026_auto_20180104_0828'),
        ('digitalglarus', '0026_auto_20180824_0739'),
    ]

    operations = [
    ]
