language: python
python:
    - "3.5"
    - "3.6"

env:
    # Set a dummy secret key
    - DJANGO_SECRET_KEY=0
# install dependencies
install: "pip install -r requirements.txt"
script:
- flake8
- python manage.py test
