# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-13 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import membership.models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20160526_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='validation_slug',
            field=models.CharField(db_index=True, default=membership.models.get_validation_slug, max_length=50, unique=True),
        ),
    ]
