# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0002_sectionwithimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionwithimage',
            name='menu_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='menu_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ungelichcontactussection',
            name='menu_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ungelichtextsection',
            name='menu_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
