# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-17 15:19
from __future__ import unicode_literals

import djangocms_text_ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0003_ungelichtextsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungelichtextsection',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(),
        ),
    ]
