# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-19 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0004_auto_20171019_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ungelichcontactussection',
            name='address',
            field=models.CharField(blank=True, default='In der Au 7, Schwanden 8762', max_length=100),
        ),
        migrations.AddField(
            model_name='ungelichcontactussection',
            name='contact_form_header_text',
            field=models.CharField(blank=True, default='Send us a message.', max_length=100),
        ),
        migrations.AddField(
            model_name='ungelichcontactussection',
            name='contact_text',
            field=models.CharField(blank=True, default='Contact', max_length=100),
        ),
        migrations.AddField(
            model_name='ungelichcontactussection',
            name='country',
            field=models.CharField(blank=True, default='Switzerland', max_length=100),
        ),
        migrations.AddField(
            model_name='ungelichcontactussection',
            name='organization_name',
            field=models.CharField(blank=True, default='ungleich GmbH', max_length=100),
        ),
        migrations.AlterField(
            model_name='ungelichcontactussection',
            name='email',
            field=models.EmailField(default='info@ungleich.ch', max_length=200),
        ),
    ]
