# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-17 10:11
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0006_aboutitem_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungelichpicture',
            name='title',
            field=djangocms_text_ckeditor.fields.HTMLField(),
        ),
    ]
