# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-21 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0010_auto_20171119_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='UngleichProduct',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ungleich_page.Service')),
                ('section_class', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('ungleich_page.service',),
        ),
        migrations.CreateModel(
            name='UngleichProductItem',
            fields=[
                ('serviceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ungleich_page.ServiceItem')),
                ('url', models.URLField(blank=True, default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
            bases=('ungleich_page.serviceitem',),
        ),
    ]
