# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-23 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20160404_1908'),
        ('ungleich_page', '0012_ungleichcustomer_ungleichcustomeritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UngleichHTMLOnly',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('HTML', djangocms_text_ckeditor.fields.HTMLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
