# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-19 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0015_ungleichsimpleheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='UngleichHeaderItemWithVideo',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True,
                                                             on_delete=django.db.models.deletion.SET_NULL, related_name='ungleich_header_item_poster', to='filer.Image')),
                ('btn_link', models.URLField(blank=True, null=True)),
                ('btn_text', models.CharField(blank=True, max_length=50, null=True)),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('video', filer.fields.file.FilerFileField(blank=True, null=True,
                                                           on_delete=django.db.models.deletion.SET_NULL, related_name='ungleich_header_item_video', to='filer.File')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
