# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-19 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0016_ungleichheaderwithbackgroundimageslider_ungleichheaderwithbackgroundimageslideritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UngleichHeaderWithBackgroundVideoSliderItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('description', models.TextField(
                    blank=True, help_text='An optional description for this slide.', null=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='The background image or poster image for video.',
                                                             null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ungleich_header_item_poster', to='filer.Image')),
                ('btn_link', models.URLField(
                    blank=True, help_text='If this field is left empty, no button would be displayed.', null=True)),
                ('btn_text', models.CharField(
                    blank=True, help_text='Text for the button, if a link is provided.', max_length=50, null=True)),
                ('heading', models.CharField(
                    blank=True, help_text='An optional title for this slide.', max_length=100, null=True)),
                ('video', filer.fields.file.FilerFileField(blank=True, help_text='Leaving this blank will make the image as the background.',
                                                           null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ungleich_header_item_video', to='filer.File')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
