# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0016_ungleichheaderwithbackgroundimageslider_ungleichheaderwithbackgroundimageslideritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_service', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_serviceitem', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='ungelichcontactussection',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_ungelichcontactussection', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='ungelichpicture',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_ungelichpicture', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='ungelichtextsection',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_ungelichtextsection', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='ungleichcustomeritem',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_ungleichcustomeritem', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='ungleichheader',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_ungleichheader', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='ungleichheaderitem',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_ungleichheaderitem', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='ungleichheaderwithbackgroundimageslider',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_ungleichheaderwithbackgroundimageslider', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='ungleichheaderwithbackgroundimageslideritem',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_ungleichheaderwithbackgroundimageslideritem', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='ungleichhtmlonly',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_ungleichhtmlonly', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='ungleichsimpleheader',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ungleich_page_ungleichsimpleheader', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
