# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-08 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0018_ungleichfooter'),
        ('ungleich_page', '0018_auto_20180105_1826'),
    ]

    operations = [
    ]
