# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-19 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0019_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungleichheaderwithbackgroundvideoslideritem',
            name='btn_link',
            field=models.CharField(blank=True, help_text='Url or #id to navigate on click. If this field is left empty, no button would be displayed.', max_length=100, null=True),
        ),
    ]
