# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-28 04:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('ungleich_page', '0020_auto_20180320_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='ungleichheaderwithbackgroundvideoslideritem',
            name='image_portrait',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Optional background image or poster image for video (for tall screens).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ungleich_header_item_poster_sm', to='filer.Image', verbose_name='Image (portrait)'),
        ),
        migrations.AlterField(
            model_name='ungleichheaderwithbackgroundvideoslideritem',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='The background image or poster image for video.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ungleich_header_item_poster', to='filer.Image'),
        ),
    ]
