BBBB BBBB BBBBBBBBB BBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXX


  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBB BBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
      XXXX
    XXXXXX    
    XXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX
          
        XXXXX
      XXXX
      XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XX FFFFFFFFFFFFFFFFFF
      XXXX

      XX XXXXXXXXXXXXXXXXXXXXXX
        BB BBB BBBBBBBBBBBBBBBB       
        BBBBBBBBBBBB BBBB BBBBBBBBBB
        BBBB
        BBBBBBBBBBBB BBBB BBBBBBBBBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBB
      XXXX



    XXXXXX
  XXXXXX


XXXXXX
XXXX
