# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-09 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opennebula_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachineTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opennebula_id', models.IntegerField()),
                ('base_price', models.FloatField()),
                ('memory_price', models.FloatField()),
                ('core_price', models.FloatField()),
                ('disk_size_price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opennebula_api.VirtualMachineTemplate'),
        ),
    ]
