# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-11 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opennebula_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='template',
            new_name='vm_template',
        ),
    ]
