# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-23 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='brutto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bill',
            name='mwst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bill',
            name='mwst_percent',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='bill',
            name='netto',
            field=models.FloatField(default=0.0),
        ),
    ]
