# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-23 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20170323_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='mwst_percent',
            field=models.FloatField(default=1.08),
        ),
    ]
