# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-23 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20170323_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='bills',
            field=models.ManyToManyField(to='bill.Bill'),
        ),
    ]
