BBBB BBBBBBBB BBBBBBBBBBB
XXXX XXXX XXXXXX XXX
XXXX XXX XXXX XXXXXXXXXX XXXXX XXX XXXX XXXXXX XX XXX XXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX
	BB BBBBBBBBBBBBBBBBBB
	XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	BBBB
	XXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX
	BBBBB
	X
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXXX
	  XXXX BBBBBBBBBBBB BBBB BBBBBBB XXXXX
	  XXX XXXXXXXXXXXXXXXXXXX
	    BBBBBBBBBBBB BBBB BBBBBBBBBB BB BB BBBBBBBBBBBBBBBBBBBBBBB
	  XXXXX
	  XXXXX XXXXXXXXXXXXX
	    XXXXXX XX FFFFFFFFFFFFFFFFFF
	  XXXXXXX
	XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
