BBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBB
    BB BBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    BBBBB
BBBBBBBB BBBB

XXXX XXXXXXXXXXXXXXXXXX
  BBBBB BBBBBBB
  XXXX XXXXXXXXXX XXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
	BBBBB BBBBBBBBBBBBBBBBBBBB
      XXXXXX
    XXXXXX
  XXXXXX
  BBBBBBBB BBBBBBB
XXXXXX
