BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBB BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXX XXXXXXXXXBBBBBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBB
XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  BB BBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX
    BBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBB
    XXXX XXXXXX XXXXXX  XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX
  XXXXXX
  BBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
	XXXXXXX
      XXXX
      XXXXXXX
	
      XXXXXXXX
    XXXXX
    XXXXXXXXX
    BBBBB BBBBBBBBB
    
    BBBBBBBB
    XXXXXXXXX
    BBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBXXXXXX
XXXXXXXXXX
BBBBBBBB BBBBBBBBBBBB