BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXX XXXXXXXXXBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXX
  BBBBB BBBBBBBBBB
  XXXXXXXX
    XXXX
      BB BBBBBB gettext('Articles by')  
      BBBB BBBBBBBBBBBB gettext('Archive')  XXXXXXX BB BBBBBFFFFFFFF BBBBB
      BBBB BBBBBBBBBBBBBB gettext('Tag')  XXXXXXX FFFFFFFF
      BBBB BBBBBBBB gettext('Category')  XXXXXXX BBBBB
    XXXXX
  XXXXXXXXX
  BBBBBBBB
  BBB BBBB BB BBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB
  XX XXXXXXXXXXXXXXXXXXX gettext('No article found.') XXXX
  BBBBBB
  BB BBBBBB BB BBBBBBBBBBBB BB BBBBBBBBBBBBBB
  XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext('Back') XXXXXXXX
  BBBBB
  BB BBBBBBBBBBBB
  XXXX XXXXX XXX
  XXX XXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX
	XXXXXXX  gettext('Newer Posts') 
      XXXX
    XXXXX
    BBBBB
    BB BBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXX
      XX XXXXXXXXXX
	 gettext('Older Posts')  XXXXXX
      XXXX
    XXXXX
    BBBBB
  XXXXX
  BBBBB
XXXXXXXXXX
BBBBBBBB
BBBBBBBBBBBB