BBBB BBBBBBBB
XXX XX
XXXX XXXXXX XXX
XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
	  XXXX
	    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	      XXXXX XXXXXXXXXXXXXXX XXXXXXX
		XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
		XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
	      XXXXXXX
	    XXXX
	  XXXXX
	  XXXX
	    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	      XXXXX XXXXXXXXXXXXXXX XXXXXXX
		XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
		XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
	      XXXXXXX
	    XXXX
	  XXXXX
	  XXXX
	    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	      XXXXX XXXXXXXXXXXXXXX XXXXXXX
		XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
		XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
	      XXXXXXX
	    XXXX
	  XXXXX
	XXXXX
	XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
	  BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
	XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
