BBBB BBBBBBBBB BBBBBBBBBBB BBBBBBBB
XXXX XXXXXXXXXX XXX
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXX XXX XXXXXX XXX XXXXXXX XXX XXXXXX XXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
      XXXX
    XXXXXX

    XXXX XXXXXXX XXX XXX XXXXXX XXXXXX XXX XXXXX XXXXXXX XXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
	BBB BBBBB BB BBBBBBBB
	XXX XXXXXXXXXXXXBB BBBBBBBBBBBBBB XXXXXXXXBBBBBBB BBBBBBBBBBBBBB XXXXXXXXBBBBBBB BBBBBBBBBBBBB XXXXXXXBBBBBBB BBBBBBBBBBBBBBBB XXXXXXXXXXBBBBBXX
	  XX XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXX
	  BB BBBBBBBBBBBBBB
	  XXXX
	    BBBBBBBBB BBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBB BB BB BBBBB
	  XXXXX
	  BBBBB
	XXXXX
	BBBBBB
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXX
  XXXX XXXXXXXXXXX XXX
XXXXXX
