BBBB  BBBBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXX XXXXXXX XXXXXXX XXX XXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
  BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXX BB BBBBBBBBBBBBB XXXXXX BBBBB XX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX  XXXXXX  XXXXXXX
    XXXXXX
  BBBBBB
  XXXXXX

  XXXX XXXXXXXX XXX
  XX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX
  XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX
XXXXXX
