BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB 
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXX XXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
	XXXXXXXXX
	  XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXXXXX
      XXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
      XXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
      XXX XXXXXXXXXXXXXXXXXXX
      BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
      XXXX
      BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
      XXXX
      BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX
XXXXXX
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
      XXXX
      BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BBBBBBBB
