BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB BBBBBBBB
BBBBB BBBBBXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX


XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
      XXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
      BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXX XXX
BBBBBBBB
