BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB BBBBBBBB
BBBBB BBBBBXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX

XXXXXX
XXXX XXXXXXXXXXX XXX

BBBBBBBB
