BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB BBBBBBBB
BBBBB BBBBBXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      BBBBBBBBBBB BBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      BBBBBBBBBBB BBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX

XXXXXX
XXXX XXXXXXXXXXX XXX

BBBBBBBB
