BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB BBBBBBBB
BBBBB BBBBBXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXX
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
      XXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
      BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX

XXXXXX
XXXX XXXXXXXXXXX XXX

BBBBBBBB
