BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBBBXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
	BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX
      XXXXX XXX XXXX XXXXXXX XXXXXXXXXXX XX XXXXXXX XXXXXXX XXXXXX XXXX XX X XXXXXXX XXXXX XXX XXXX XXXXXXXXXX
      XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXX
	BBBBBBBBBB
	XXXX XXXXXXXXXXXX
	  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
	    XXXXXXXXXXXXXXXXXXX
	    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
	  XXXXXX
	  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
	    XXXXXXXXXXXX XXXXXXXXXXXXXXX
	    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
	  XXXXXX
	  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
	    XXXXXXXXXXXX XXXXXXXXXXXXXX
	    XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
	  XXXXXX
	  XXXX XXXXXXXXXXXXXXXXXXXXXXX
	  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
	    XXXXXXXXXXXXXXXXXXXXXX
	    XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
	  XXXXXX
	  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
	    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
	    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
	  XXXXXX
	XXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXX
XXXX XXXXXXXXXXX XXX
BBBBBBBB
