BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBBB BBBBBXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXX XXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
      XXXXXXXXXXXXX
	XXXXXXX XXXXXXXXXXXXXXXXX
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
      XXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
      XXXXXXXXXX
	XXXXXXX XXXXXXXXXX XX XXXXXXXXXXXXXX
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX
XXXX XXXXXXXXXXX XXX
BBBBBBBB
