BBBB BBBB BBBBBBBB BBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBB
XXXX XXXX XXXXXX XXX
XXXX XXX XXXX XXXXXXXXXX XXXXX XXX XXXX XXXXXX XX XXX XXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX
	BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
	XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	BBBB
	XXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX
	BBBBB
	X

  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXX

			BB BBBBBBBBBBBBBBBB B B
			    XXXX XXXXXXXXXXXXXXXXXXXXX
			    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
			        BBB BBBBBBBB BB BBBBBBBBB
			            XXX XXXXXXXXXXXBB BBBBBBBBBBBBBBBB BB BBBBBBBBBB XXXXXXBBBBBXX
			                XX XXXXXXBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
			                   XXXXXXX gettext('Change to language:')  XXXXXX
			            XXXXX
			        BBBBBB
			    XXXXX
			    XXXXXX
			BBBBB


		  XXXX BBBBBBBBBBBBBB BBBBBBBBBBBB  XXXXX
		  XXX XXXXXXXXXXXXXX
		  XXXXX XXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXX
		XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
