# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-06 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipv6cat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Cat',
        ),
    ]
