# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-06 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipv6cat', '0002_auto_20180407_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
