# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20161013_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
