# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20170322_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='cardholder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userbillingaddress',
            name='cardholder_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
