BBBBBBB  BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBB
    BB BBBB
	BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    BBBBB
BBBBBBBB BBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXXXX XXXXXXX
  BBBBB BBBBBBBBBBBBBBBBBBBB
XXXXXX
BBBBBBBB BBBBBBB