# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nosystemd', '0003_donatorstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatorstatus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='donatorstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
