XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXX X XXX XXXXXXX
    XXX XXXXX X XXXXXXXXXXXXXXX X XX
    XXX XXXX X XXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXX X XXX
    XXX XXXXXXXXXXXXXXXXXXXXXX X XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX X XXX X XXXXX XXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XX X
                XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXX X
                    XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX X
                        XXXXXXXXX X XXXXXXXXXXXXXXXX X XXX XXXXXX
                                XXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                    X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
                XXXXXXXXXXXXXXXXXXXXXX
            XX
        XXX
    XX

XXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXX XXXXXXXX XXX
XXXXXX XXXX XXX XXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX X XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXX X XXXXXXXXXXXXXXXX X XXX XXXXXX
                    XXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX X
            XXXXXXXXX X XXXXXXXXXXXXXXXX X XXX XXXXXX
                    XXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX
    X
    XXXXXXXX XXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX X XX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX X
            XX XXXXXXXXXXXXXX XXXXXXX XXX XXX XXXXXXXXXXXXXXXX
        XXX
        XXXXXXXXXXXXXX X XXXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
                    X XXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
                    X
                    XXXXXXXXXXXXXXX

                    XXXXXXXXX X XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XX X XXX X XXXXXXXXXXXXXXXXXXX
                            XXXXXXXX XXXXXX X
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX
                XX
                XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XX X

                    XXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXX
                            XXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXX X
                                XX XXXXXXXXXXXXXXXXXXX X
                                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
                                X
                            X
                        XXX
                        XXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXX X XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX X
                            XX XXXXXXXXXXXX XX XXXXXXXXXX X
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXX XX X
                                    XXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXXX
                                XX XXXX
                            X
                        XX
                    X XXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
                    X
                XXX
    X
XXXXXXXXX
