BBBB BBBBBB BBBBBBBBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX

XXXXXX

    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXX



    XXXX XXXXXXXXX XXXX XXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXX XXXXXX XXXXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXX XXXXXX XXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXX XXXXX XXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX


    XXXX XXXXX XXXX XXX XXXXXXXXXX XXX XXXXXXX XX XXXXX XXXXXXXX XXX XXXXX XXXXXXX XXX
    XXXX XXXXXXXX XXXXXXXXXX XXXXXXX XXXX XX XXX XXXX XXX XXXX XXX XXXXXXX XXX
    XXXXXXX XX XX XXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX

XXXXXXX

XXXXX XXXXXXXXXXXXXX    

    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXX XXX XXXXXX XXX XXXXXXX XXX XXXXXX XXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXX
                
                 XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXX XXXX XXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXX XXX XXX XXXXXX XXXXXX XXX XXXXX XXXXXXX XXX XXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
XXXX                     XXXX
                        XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXX
                        XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXX
                        XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext('My Donations')  XXXX
                    XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                          XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext('Logout')  XXXXXXXXX
                          XXXXX
                        XXXXX              
                    BBBB
                        XXXX
                            XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX
                        XXXXX 
                    BBBBB
                XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXX

    BBBBB BBBBBBB
    BBBBBBBB

    XXXX XXXXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXX XXXXXXXXX XXXX XXXXXXXXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXX XXXXXX XXXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXX XXXXX XXXXXXXXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXX XXXXXX XXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXX XXXXXXX XXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXXXXX

XXXXXXX